repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
    - id: generate-sphinx-docs
      name: Generate Sphinx Docs
      entry: bash -c "cd docs && make clean && make html"
      language: system
      pass_filenames: false
      always_run: true

- repo: https://github.com/pylint-dev/pylint
  rev: v3.3.1
  hooks:
    - id: pylint
      name: Pylint
      entry: pylint
      language: python
      types: [python]
